import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "eye-tracking",
	title: "Eye Tracking",
	description: "",
	interaction: "",
	categories: ["Cursor & Pointer Effects"],
	tags: ["spring", "cursor-tracking", "autoplay"],
	inspiration: {
		source: "Componentry",
		url: "https://www.componentry.fun/docs/components/eye-tracking",
		authorUrl: "https://www.componentry.fun",
		relationship: "adaptation",
	},
	dependencies: ["motion"],
	registryDependencies: [],
	props: [
		{ name: "className", type: "string", description: "Additional CSS classes" },
		{ name: "eyeSize", type: "number", default: "120", description: "Size of each eye in pixels" },
		{ name: "gap", type: "number", default: "40", description: "Gap between eyes in pixels" },
		{ name: "irisColor", type: "string", default: "\"#4A6741\"", description: "Color of the iris" },
		{ name: "irisColorSecondary", type: "string", default: "\"#6B8F62\"", description: "Secondary iris color for gradient" },
		{ name: "pupilColor", type: "string", default: "\"#0a0a0a\"", description: "Pupil color" },
		{ name: "scleraColor", type: "string", default: "\"#F5F0EB\"", description: "Sclera (white) color" },
		{ name: "pupilRange", type: "number", default: "0.7", description: "How far the pupil can travel (0-1)" },
		{ name: "showReflection", type: "boolean", default: "true", description: "Enable the reflection/glint effect" },
		{ name: "showIrisDetail", type: "boolean", default: "true", description: "Enable iris detail pattern" },
		{ name: "idleAnimation", type: "boolean", default: "true", description: "Enable subtle idle animation when cursor is away" },
		{ name: "blinkInterval", type: "number", default: "4000", description: "Blink interval in milliseconds (0 to disable)" },
		{ name: "eyeCount", type: "number", default: "2", description: "Number of eyes" },
		{ name: "variant", type: "\"realistic\" | \"cartoon\" | \"minimal\" | \"cyber\"", default: "\"realistic\"", description: "Variant style" },
		{ name: "reactivePupil", type: "boolean", default: "true", description: "Enable reactive pupil dilation" },
		{ name: "showEyelids", type: "boolean", default: "true", description: "Eyelid visibility" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
