import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "grainient",
	title: "Grainient",
	description: "",
	interaction: "",
	categories: ["Backgrounds"],
	tags: ["webgl", "autoplay", "responsive"],
	dependencies: ["ogl"],
	registryDependencies: [],
	props: [
		{ name: "timeSpeed", type: "number", default: "0.25" },
		{ name: "colorBalance", type: "number", default: "0.0" },
		{ name: "warpStrength", type: "number", default: "1.0" },
		{ name: "warpFrequency", type: "number", default: "5.0" },
		{ name: "warpSpeed", type: "number", default: "2.0" },
		{ name: "warpAmplitude", type: "number", default: "50.0" },
		{ name: "blendAngle", type: "number", default: "0.0" },
		{ name: "blendSoftness", type: "number", default: "0.05" },
		{ name: "rotationAmount", type: "number", default: "500.0" },
		{ name: "noiseScale", type: "number", default: "2.0" },
		{ name: "grainAmount", type: "number", default: "0.1" },
		{ name: "grainScale", type: "number", default: "2.0" },
		{ name: "grainAnimated", type: "boolean", default: "false" },
		{ name: "contrast", type: "number", default: "1.5" },
		{ name: "gamma", type: "number", default: "1.0" },
		{ name: "saturation", type: "number", default: "1.0" },
		{ name: "centerX", type: "number", default: "0.0" },
		{ name: "centerY", type: "number", default: "0.0" },
		{ name: "zoom", type: "number", default: "0.9" },
		{ name: "color1", type: "string", default: "'#FF9FFC'" },
		{ name: "color2", type: "string", default: "'#5227FF'" },
		{ name: "color3", type: "string", default: "'#B19EEF'" },
		{ name: "className", type: "string", default: "''" },
	],
	risk: { heavy: true, fullscreen: true, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
