import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "faulty-terminal",
	title: "Faulty Terminal",
	description: "",
	interaction: "",
	categories: ["Backgrounds"],
	tags: ["webgl", "cursor-tracking", "autoplay", "responsive"],
	dependencies: ["ogl"],
	registryDependencies: [],
	props: [
		{ name: "scale", type: "number", default: "1" },
		{ name: "gridMul", type: "Vec2", default: "[2, 1]" },
		{ name: "digitSize", type: "number", default: "1.5" },
		{ name: "timeScale", type: "number", default: "0.3" },
		{ name: "pause", type: "boolean", default: "false" },
		{ name: "scanlineIntensity", type: "number", default: "0.3" },
		{ name: "glitchAmount", type: "number", default: "1" },
		{ name: "flickerAmount", type: "number", default: "1" },
		{ name: "noiseAmp", type: "number", default: "1" },
		{ name: "chromaticAberration", type: "number", default: "0" },
		{ name: "dither", type: "number | boolean", default: "0" },
		{ name: "curvature", type: "number", default: "0.2" },
		{ name: "tint", type: "string", default: "\"#ffffff\"" },
		{ name: "mouseReact", type: "boolean", default: "true" },
		{ name: "mouseStrength", type: "number", default: "0.2" },
		{ name: "dpr", type: "number", default: "Math.min(window.devicePixelRatio || 1…" },
		{ name: "pageLoadAnimation", type: "boolean", default: "true" },
		{ name: "brightness", type: "number", default: "1" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
