import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "depth-text",
	title: "Depth Text",
	description: "",
	interaction: "",
	categories: ["Text Animations"],
	tags: ["hover", "cursor-tracking", "autoplay", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/text-animations/depth-text",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: [],
	registryDependencies: [],
	props: [
		{ name: "text", type: "string", default: "'Elevate'" },
		{ name: "layers", type: "number", default: "34" },
		{ name: "depth", type: "number", default: "2.4" },
		{ name: "faceColor", type: "string", default: "'#f8fafc'" },
		{ name: "depthColor", type: "string", default: "'#7c3aed'" },
		{ name: "tilt", type: "number", default: "7.5" },
		{ name: "pointerTracking", type: "boolean", default: "true" },
		{ name: "smoothing", type: "number", default: "0.14" },
		{ name: "perspective", type: "number", default: "900" },
		{ name: "autoOrbit", type: "boolean", default: "true" },
		{ name: "orbitSpeed", type: "number", default: "0.35" },
		{ name: "fontSize", type: "string", default: "'clamp(3rem, 12vw, 7rem)'" },
		{ name: "fontWeight", type: "string | number", default: "900" },
		{ name: "shadow", type: "boolean", default: "true" },
		{ name: "className", type: "string", default: "''" },
		{ name: "style", type: "CSSProperties", default: "{}" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
