import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "inflected-card",
	title: "Inflected Card",
	description: "",
	interaction: "",
	categories: ["Cards"],
	tags: ["hover"],
	inspiration: {
		source: "Namer UI",
		url: "https://namer-ui.netlify.app/components",
		authorUrl: "https://namer-ui.netlify.app",
		relationship: "adaptation",
	},
	dependencies: ["@tabler/icons-react"],
	registryDependencies: [],
	props: [
		{ name: "id", type: "string", required: true },
		{ name: "image", type: "string", required: true },
		{ name: "title", type: "string", required: true },
		{ name: "description", type: "string", required: true },
		{ name: "tags", type: "Tag[]", required: true },
		{ name: "parentBackgroundColor", type: "string", required: true },
		{ name: "buttonIcon", type: "React.ReactElement<unknown, string | React.JSXElementCons…", required: true },
		{ name: "onClick", type: "((hoverTarget: string, id: string) => void)" },
		{ name: "onHover", type: "((hoverTarget: string, id: string) => void)" },
		{ name: "cardRounding", type: "number", default: "20" },
		{ name: "fontSizes", type: "{ title?: string; description?: string; tags?: string; pr…", default: "{}" },
		{ name: "margins", type: "{ title?: string; description?: string; tags?: string; }", default: "{}" },
		{ name: "buttonIconSize", type: "number", default: "24" },
		{ name: "buttonIconColor", type: "string", default: "'#fff'" },
		{ name: "buttonIconHoverColor", type: "string", default: "'#fff'" },
		{ name: "buttonBackgroundColor", type: "string", default: "'#282828'" },
		{ name: "buttonBackgroundHoverColor", type: "string", default: "'#484848'" },
		{ name: "imageHoverZoom", type: "number", default: "1.1" },
		{ name: "titleColor", type: "string", default: "'#f7f7ff'" },
		{ name: "descriptionColor", type: "string", default: "'#c7c7cf'" },
		{ name: "mirrored", type: "boolean", default: "false" },
		{ name: "titleAlignment", type: "\"left\" | \"center\" | \"right\"", default: "'left'" },
		{ name: "descriptionAlignment", type: "\"left\" | \"center\" | \"right\"", default: "'left'" },
		{ name: "tagsAlignment", type: "\"left\" | \"center\" | \"right\"", default: "'left'" },
		{ name: "maxWidth", type: "string", default: "'100%'" },
		{ name: "price", type: "string" },
		{ name: "priceTagTextColor", type: "string", default: "'#ffffff'" },
		{ name: "oldPrice", type: "string" },
		{ name: "oldPriceOnTheRight", type: "boolean", default: "false" },
		{ name: "oldPriceTextColor", type: "string", default: "'#c1c1c7'" },
		{ name: "priceTagRounding", type: "string", default: "'5px'" },
		{ name: "priceTagBackgroundColor", type: "string", default: "'rgba(0,0,0,0.7)'" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
