import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "cascade-page-transition",
	title: "Cascade Page Transition",
	description: "A vibrant, cascading full-screen page transition where columns or rows sweep in an in-to-out or out-to-in V-pattern with optional edge stroke outline accents.",
	interaction: "Programmatically triggered on route change or view swaps, showing a cascade of colored stripes with customizable borders.",
	categories: ["Special Effects & FX"],
	tags: [],
	inspiration: {
		source: "Great UI",
		url: "https://www.great-ui.com/components/cascade-page-transition",
		author: "Saurabh Sharma",
		authorUrl: "https://github.com/Saurabh-2607",
		license: "Great UI Custom License",
		relationship: "port",
	},
	dependencies: ["motion"],
	registryDependencies: [],
	props: [
		{ name: "trigger", type: "number", required: true },
		{ name: "onViewSwap", type: "(() => void)" },
		{ name: "className", type: "string" },
		{ name: "panelClassName", type: "string" },
		{ name: "columns", type: "number", default: "14" },
		{ name: "colors", type: "string[]", default: "defaultPalette" },
		{ name: "duration", type: "number", default: "0.55" },
		{ name: "staggerDelay", type: "number", default: "0.035" },
		{ name: "ease", type: "Easing | Easing[]", default: "[0.76, 0, 0.24, 1]" },
		{ name: "direction", type: "\"bottom\" | \"left\" | \"right\" | \"top\"", default: "\"top\"" },
		{ name: "exitOpposite", type: "boolean", default: "true" },
		{ name: "mode", type: "\"in-to-out\" | \"out-to-in\"", default: "\"in-to-out\"" },
		{ name: "showLeadingStroke", type: "boolean", default: "false" },
		{ name: "showTrailingStroke", type: "boolean", default: "false" },
		{ name: "strokeWidth", type: "number", default: "10" },
		{ name: "leadingStrokeColors", type: "string[]", default: "defaultPalette" },
		{ name: "trailingStrokeColors", type: "string[]", default: "defaultPalette" },
	],
	risk: { heavy: false, fullscreen: true, clientOnly: false },
	rating: 5,
	status: "needs-review",
	gated: true,
});
