import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "laser-flow",
	title: "Laser Flow",
	description: "",
	interaction: "",
	categories: ["Backgrounds"],
	tags: ["webgl", "cursor-tracking", "autoplay", "responsive"],
	dependencies: ["three"],
	registryDependencies: [],
	props: [
		{ name: "className", type: "string" },
		{ name: "style", type: "React.CSSProperties" },
		{ name: "wispDensity", type: "number", default: "1" },
		{ name: "dpr", type: "number" },
		{ name: "mouseSmoothTime", type: "number", default: "0.0" },
		{ name: "mouseTiltStrength", type: "number", default: "0.01" },
		{ name: "horizontalBeamOffset", type: "number", default: "0.1" },
		{ name: "verticalBeamOffset", type: "number", default: "0.0" },
		{ name: "flowSpeed", type: "number", default: "0.35" },
		{ name: "verticalSizing", type: "number", default: "2.0" },
		{ name: "horizontalSizing", type: "number", default: "0.5" },
		{ name: "fogIntensity", type: "number", default: "0.45" },
		{ name: "fogScale", type: "number", default: "0.3" },
		{ name: "wispSpeed", type: "number", default: "15.0" },
		{ name: "wispIntensity", type: "number", default: "5.0" },
		{ name: "flowStrength", type: "number", default: "0.25" },
		{ name: "decay", type: "number", default: "1.1" },
		{ name: "falloffStart", type: "number", default: "1.2" },
		{ name: "fogFallSpeed", type: "number", default: "0.6" },
		{ name: "color", type: "string", default: "\"#FF79C6\"" },
	],
	risk: { heavy: true, fullscreen: true, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
