import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "scroll-expand",
	title: "Scroll Expand",
	description: "",
	interaction: "",
	categories: ["Scroll"],
	tags: ["drag", "scroll-driven", "autoplay", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/animations/scroll-expand",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: [],
	registryDependencies: [],
	props: [
		{ name: "src", type: "string", default: "''" },
		{ name: "mediaType", type: "\"image\" | \"video\"", default: "'image'" },
		{ name: "poster", type: "string", default: "''" },
		{ name: "alt", type: "string", default: "''" },
		{ name: "title", type: "string", default: "''" },
		{ name: "scrollHint", type: "string", default: "''" },
		{ name: "startWidth", type: "number", default: "42" },
		{ name: "startHeight", type: "number", default: "58" },
		{ name: "startRadius", type: "number", default: "24" },
		{ name: "endRadius", type: "number", default: "0" },
		{ name: "mediaZoom", type: "number", default: "1.35" },
		{ name: "scrollDistance", type: "number", default: "1.2" },
		{ name: "holdDistance", type: "number", default: "0.35" },
		{ name: "smoothing", type: "number", default: "0.1" },
		{ name: "overlayScrim", type: "number", default: "0.45" },
		{ name: "useWindowScroll", type: "boolean", default: "false" },
		{ name: "enabled", type: "boolean", default: "true" },
		{ name: "className", type: "string", default: "''" },
		{ name: "style", type: "CSSProperties" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
