import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "stroke-text",
	title: "Stroke Text",
	description: "",
	interaction: "",
	categories: ["Text"],
	tags: ["scroll-driven", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/text-animations/stroke-text",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: ["gsap"],
	registryDependencies: [],
	props: [
		{ name: "text", type: "string", default: "DEFAULT_TEXT" },
		{ name: "strokeColor", type: "string", default: "'#A78BFA'" },
		{ name: "fillColor", type: "string", default: "'#F8FAFC'" },
		{ name: "strokeWidth", type: "number", default: "1.4" },
		{ name: "drawDuration", type: "number", default: "1.6" },
		{ name: "fillDelay", type: "number", default: "0.2" },
		{ name: "stagger", type: "number", default: "0.05" },
		{ name: "ease", type: "string", default: "'power2.out'" },
		{ name: "trigger", type: "StrokeTextTrigger", default: "'mount'" },
		{ name: "fillMode", type: "StrokeTextFillMode", default: "'wipe'" },
		{ name: "fontSize", type: "number", default: "128" },
		{ name: "fontWeight", type: "string | number", default: "800" },
		{ name: "letterSpacing", type: "number", default: "-4" },
		{ name: "reverse", type: "boolean", default: "false" },
		{ name: "className", type: "string", default: "''" },
		{ name: "style", type: "CSSProperties", default: "{}" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
