import React from "react";

import type { Metadata } from "next";

import "./transition.css";

import { HoverProvider } from "@/lib/hover-context";
import HoverFooter from "@/registry/components/hover-footer/component";
import ResizeNavBar from "@/registry/components/resize-navbar/component";
import { GoogleAnalytics } from "@next/third-parties/google";
import { ThemeProvider } from "next-themes";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<NuqsAdapter>
					<HoverProvider>
						<ResizeNavBar />
						{children}

						<HoverFooter />
					</HoverProvider>
				</NuqsAdapter>
			</body>
			<GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_KEY} />
		</html>
	);
}
