import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "curved-input",
	title: "Curved Input",
	description: "",
	interaction: "",
	categories: ["Forms & Inputs"],
	tags: ["drag", "hover", "cursor-tracking", "keyboard", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/components/curved-input",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: [],
	registryDependencies: [],
	props: [
		{ name: "value", type: "string" },
		{ name: "defaultValue", type: "string", default: "''" },
		{ name: "onChange", type: "((value: string) => void)" },
		{ name: "onSubmit", type: "((value: string) => void)" },
		{ name: "placeholder", type: "string", default: "'Enter your email'" },
		{ name: "buttonText", type: "string", default: "'Get Started'" },
		{ name: "type", type: "string", default: "'email'" },
		{ name: "name", type: "string" },
		{ name: "ariaLabel", type: "string" },
		{ name: "theme", type: "Theme", default: "'dark'" },
		{ name: "width", type: "string | number", default: "450" },
		{ name: "bend", type: "number", default: "28" },
		{ name: "height", type: "number", default: "64" },
		{ name: "cornerRadius", type: "number", default: "18" },
		{ name: "borderWidth", type: "number", default: "1.5" },
		{ name: "fontSize", type: "number", default: "16" },
		{ name: "backgroundColor", type: "string" },
		{ name: "textColor", type: "string" },
		{ name: "placeholderColor", type: "string" },
		{ name: "borderColor", type: "string" },
		{ name: "buttonColor", type: "string" },
		{ name: "buttonTextColor", type: "string" },
		{ name: "iconColor", type: "string" },
		{ name: "shadowSize", type: "ShadowSize", default: "'md'" },
		{ name: "shadowColor", type: "string" },
		{ name: "showButton", type: "boolean", default: "true" },
		{ name: "showIcon", type: "boolean", default: "true" },
		{ name: "icon", type: "ReactNode" },
		{ name: "className", type: "string", default: "''" },
		{ name: "style", type: "CSSProperties" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
