import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "strands",
	title: "Strands",
	description: "",
	interaction: "",
	categories: ["Backgrounds"],
	tags: ["webgl", "autoplay"],
	dependencies: ["ogl"],
	registryDependencies: [],
	props: [
		{ name: "colors", type: "string[]", default: "['#FF4242', '#7C3AED', '#06B6D4', '#E…" },
		{ name: "count", type: "number", default: "3" },
		{ name: "speed", type: "number", default: "0.5" },
		{ name: "amplitude", type: "number", default: "1" },
		{ name: "waviness", type: "number", default: "1" },
		{ name: "thickness", type: "number", default: "0.7" },
		{ name: "glow", type: "number", default: "2.6" },
		{ name: "taper", type: "number", default: "3" },
		{ name: "spread", type: "number", default: "1" },
		{ name: "hueShift", type: "number", default: "0" },
		{ name: "intensity", type: "number", default: "0.6" },
		{ name: "saturation", type: "number", default: "1.5" },
		{ name: "opacity", type: "number", default: "1" },
		{ name: "scale", type: "number", default: "1.5" },
		{ name: "glass", type: "boolean", default: "false" },
		{ name: "refraction", type: "number", default: "1" },
		{ name: "dispersion", type: "number", default: "1" },
		{ name: "glassSize", type: "number", default: "1" },
		{ name: "className", type: "string", default: "''" },
		{ name: "style", type: "CSSProperties" },
	],
	risk: { heavy: true, fullscreen: true, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
