import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "line-sidebar2",
	title: "Line Sidebar2",
	description: "",
	interaction: "",
	categories: ["Navigation"],
	tags: ["cursor-tracking", "autoplay"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/components/line-sidebar",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: [],
	registryDependencies: [],
	props: [
		{ name: "items", type: "string[]", default: "DEFAULT_ITEMS" },
		{ name: "accentColor", type: "string", default: "'#A855F7'" },
		{ name: "textColor", type: "string", default: "'#c4c4c4'" },
		{ name: "markerColor", type: "string", default: "'#6c6c6c'" },
		{ name: "showIndex", type: "boolean", default: "true" },
		{ name: "showMarker", type: "boolean", default: "true" },
		{ name: "proximityRadius", type: "number", default: "100" },
		{ name: "maxShift", type: "number", default: "30" },
		{ name: "falloff", type: "Falloff", default: "'smooth'" },
		{ name: "markerLength", type: "number", default: "60" },
		{ name: "markerGap", type: "number", default: "0" },
		{ name: "tickScale", type: "number", default: "0.5" },
		{ name: "scaleTick", type: "boolean", default: "true" },
		{ name: "itemGap", type: "number", default: "20" },
		{ name: "fontSize", type: "number", default: "1.1" },
		{ name: "smoothing", type: "number", default: "100" },
		{ name: "defaultActive", type: "number | null", default: "null" },
		{ name: "onItemClick", type: "((index: number, label: string) => void)" },
		{ name: "className", type: "string", default: "''" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
