import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "github-card",
	title: "Github Card",
	description: "A customizable hover link component that reveals a realistic 3D-tilted GitHub contributions calendar popup with interactive tooltips.",
	interaction: "Hover-triggered 3D card rotation, coordinate tracking, contribution block micro-scaling, and interactive cell tooltips.",
	categories: ["Cards"],
	tags: ["spring", "hover", "cursor-tracking", "theme-aware"],
	inspiration: {
		source: "Great UI",
		url: "https://www.great-ui.com/components/github-card",
		author: "Saurabh Sharma",
		authorUrl: "https://github.com/Saurabh-2607",
		license: "Great UI Custom License",
		relationship: "port",
	},
	dependencies: ["motion", "next-themes"],
	registryDependencies: [],
	props: [
		{ name: "username", type: "string", required: true },
		{ name: "name", type: "string", default: "\"GitHub User\"" },
		{ name: "avatarUrl", type: "string" },
		{ name: "year", type: "string | number", default: "2026" },
		{ name: "text", type: "string", default: "\"Follow me on\"" },
		{ name: "linkText", type: "string", default: "\"GitHub\"" },
		{ name: "href", type: "string" },
		{ name: "themeScheme", type: "\"monochrome\" | \"green\" | \"blue\" | \"purple\"", default: "\"monochrome\"" },
		{ name: "calendarTheme", type: "{ light: string[]; dark: string[]; }" },
		{ name: "contributionsData", type: "{ date: string; count: number; level: number; }[]" },
		{ name: "totalContributions", type: "number" },
		{ name: "enableLinkTilt", type: "boolean", default: "true" },
		{ name: "linkTiltMaxRotate", type: "number", default: "5" },
		{ name: "enableCardTilt", type: "boolean", default: "true" },
		{ name: "cardTiltMaxRotate", type: "number", default: "5" },
		{ name: "className", type: "string" },
		{ name: "popoverClassName", type: "string" },
		{ name: "linkClassName", type: "string" },
		{ name: "labelClassName", type: "string" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
	gated: true,
});
