import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "elastic-mesh",
	title: "Elastic Mesh",
	description: "",
	interaction: "",
	categories: ["Special Effects & FX"],
	tags: ["webgl", "cursor-tracking", "autoplay", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/animations/elastic-mesh",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: ["ogl"],
	registryDependencies: [],
	props: [
		{ name: "image", type: "string", default: "''" },
		{ name: "color1", type: "string", default: "'#5227FF'" },
		{ name: "color2", type: "string", default: "'#B19EEF'" },
		{ name: "highlight", type: "string", default: "'#ffffff'" },
		{ name: "showGrid", type: "boolean", default: "true" },
		{ name: "gridDensity", type: "number", default: "20" },
		{ name: "gridOpacity", type: "number", default: "0.28" },
		{ name: "gridColor", type: "string", default: "'#ffffff'" },
		{ name: "borderRadius", type: "number", default: "25" },
		{ name: "stiffness", type: "number", default: "0.05" },
		{ name: "damping", type: "number", default: "0.2" },
		{ name: "grabRadius", type: "number", default: "0.6" },
		{ name: "pull", type: "number", default: "0.4" },
		{ name: "wobble", type: "number", default: "5" },
		{ name: "tilt", type: "number", default: "14" },
		{ name: "shading", type: "number", default: "0.5" },
		{ name: "resolution", type: "number", default: "25" },
		{ name: "interaction", type: "\"hover\" | \"drag\"", default: "'hover'" },
		{ name: "enabled", type: "boolean", default: "true" },
		{ name: "className", type: "string", default: "''" },
		{ name: "style", type: "CSSProperties" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
