import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "text-type",
	title: "Text Type",
	description: "",
	interaction: "",
	categories: ["Text", "Text Animations"],
	tags: ["scroll-driven"],
	dependencies: ["gsap"],
	registryDependencies: [],
	props: [
		{ name: "text", type: "string | string[]", required: true },
		{ name: "className", type: "string", default: "\"\"" },
		{ name: "showCursor", type: "boolean", default: "true" },
		{ name: "hideCursorWhileTyping", type: "boolean", default: "false" },
		{ name: "cursorCharacter", type: "ReactNode", default: "\"|\"" },
		{ name: "cursorBlinkDuration", type: "number", default: "0.5" },
		{ name: "cursorClassName", type: "string", default: "\"\"" },
		{ name: "as", type: "ElementType" },
		{ name: "typingSpeed", type: "number", default: "50" },
		{ name: "initialDelay", type: "number", default: "0" },
		{ name: "pauseDuration", type: "number", default: "2000" },
		{ name: "deletingSpeed", type: "number", default: "30" },
		{ name: "loop", type: "boolean", default: "true" },
		{ name: "textColors", type: "string[]", default: "[]" },
		{ name: "variableSpeed", type: "{ min: number; max: number; }" },
		{ name: "onSentenceComplete", type: "((sentence: string, index: number) => void)" },
		{ name: "startOnVisible", type: "boolean", default: "false" },
		{ name: "reverseMode", type: "boolean", default: "false" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
