import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "color-wipe-page-transition",
	title: "Color Wipe Page Transition",
	description: "A fast, colorful screen transition featuring staggered horizontal bands with vibrant doodle accents.",
	interaction: "Programmatically triggered. Covers the screen horizontally with 10 staggered lines before sliding out to reveal the new state.",
	categories: ["Special Effects & FX"],
	tags: [],
	inspiration: {
		source: "Great UI",
		url: "https://www.great-ui.com/components/color-wipe-page-transition",
		author: "Saurabh Sharma",
		authorUrl: "https://github.com/Saurabh-2607",
		license: "Great UI Custom License",
		relationship: "port",
	},
	dependencies: ["motion"],
	registryDependencies: [],
	props: [
		{ name: "trigger", type: "number", required: true },
		{ name: "onViewSwap", type: "(() => void)" },
		{ name: "panelColor", type: "string" },
		{ name: "columns", type: "number", default: "10" },
		{ name: "duration", type: "number", default: "0.45" },
		{ name: "staggerDelay", type: "number", default: "0.03" },
		{ name: "ease", type: "Easing | Easing[]", default: "[0.85, 0, 0.15, 1]" },
		{ name: "direction", type: "\"bottom\" | \"left\" | \"right\" | \"top\"", default: "\"left\"" },
		{ name: "exitOpposite", type: "boolean", default: "false" },
		{ name: "showLeadingStroke", type: "boolean", default: "true" },
		{ name: "showTrailingStroke", type: "boolean", default: "true" },
		{ name: "strokeWidth", type: "number", default: "10" },
		{ name: "leadingStrokeColors", type: "string[]", default: "[ \"#facc15\", \"#ec4899\", \"#38bdf8\", \"#…" },
		{ name: "trailingStrokeColors", type: "string[]", default: "[ \"#facc15\", \"#ec4899\", \"#38bdf8\", \"#…" },
	],
	risk: { heavy: false, fullscreen: true, clientOnly: false },
	rating: 5,
	status: "needs-review",
	gated: true,
});
