import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "text-along-path",
	title: "Text Along Path",
	description: "",
	interaction: "",
	categories: ["Text", "Text Animations"],
	tags: ["scroll-driven"],
	inspiration: {
		source: "Fancy Components",
		url: "https://www.fancycomponents.dev/docs/components/text/text-along-path",
		authorUrl: "https://www.fancycomponents.dev",
		relationship: "adaptation",
	},
	dependencies: ["motion"],
	registryDependencies: [],
	props: [
		{ name: "path", type: "string", required: true },
		{ name: "text", type: "string", required: true },
		{ name: "pathId", type: "string" },
		{ name: "pathClassName", type: "string" },
		{ name: "preserveAspectRatio", type: "PreserveAspectRatio", default: "\"xMidYMid meet\"" },
		{ name: "showPath", type: "boolean", default: "false" },
		{ name: "width", type: "string | number", default: "\"100%\"" },
		{ name: "height", type: "string | number", default: "\"100%\"" },
		{ name: "viewBox", type: "string", default: "\"0 0 100 100\"" },
		{ name: "svgClassName", type: "string" },
		{ name: "textClassName", type: "string" },
		{ name: "textAnchor", type: "\"start\" | \"middle\" | \"end\"", default: "\"start\"" },
		{ name: "animationType", type: "\"auto\" | \"scroll\"", default: "\"auto\"" },
		{ name: "duration", type: "number", default: "4" },
		{ name: "repeatCount", type: "number | \"indefinite\"", default: "\"indefinite\"" },
		{ name: "easingFunction", type: "{ calcMode?: string; keyTimes?: string; keySplines?: stri…", default: "{}" },
		{ name: "scrollContainer", type: "RefObject<HTMLElement>" },
		{ name: "scrollOffset", type: "any", default: "[\"start end\", \"end end\"]" },
		{ name: "scrollTransformValues", type: "[number, number]", default: "[0, 100]" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
