import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "lightfall",
	title: "Lightfall",
	description: "",
	interaction: "",
	categories: ["Backgrounds"],
	tags: ["webgl", "cursor-tracking", "autoplay", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://www.reactbits.dev/backgrounds/lightfall",
		authorUrl: "https://www.reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: ["ogl"],
	registryDependencies: [],
	props: [
		{ name: "className", type: "string" },
		{ name: "dpr", type: "number" },
		{ name: "paused", type: "boolean", default: "false" },
		{ name: "colors", type: "string[]", default: "['#A6C8FF', '#5227FF', '#FF9FFC']" },
		{ name: "backgroundColor", type: "string", default: "'#0A29FF'" },
		{ name: "speed", type: "number", default: "0.5" },
		{ name: "streakCount", type: "number", default: "2" },
		{ name: "streakWidth", type: "number", default: "1" },
		{ name: "streakLength", type: "number", default: "1" },
		{ name: "glow", type: "number", default: "1" },
		{ name: "density", type: "number", default: "0.6" },
		{ name: "twinkle", type: "number", default: "1" },
		{ name: "zoom", type: "number", default: "3" },
		{ name: "backgroundGlow", type: "number", default: "0.5" },
		{ name: "opacity", type: "number", default: "1" },
		{ name: "mouseInteraction", type: "boolean", default: "true" },
		{ name: "mouseStrength", type: "number", default: "0.5" },
		{ name: "mouseRadius", type: "number", default: "1" },
		{ name: "mouseDampening", type: "number", default: "0.15" },
		{ name: "mixBlendMode", type: "string" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
