import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "spiral-gallery",
	title: "Spiral Gallery",
	description: "",
	interaction: "",
	categories: ["Media Galleries"],
	tags: ["webgl", "spring", "cursor-tracking", "keyboard", "responsive"],
	inspiration: {
		source: "Atelier UI",
		url: "https://www.atelier-ui.com/en/docs/components/background/spiral-gallery",
		authorUrl: "https://www.atelier-ui.com",
		relationship: "adaptation",
	},
	dependencies: ["@react-three/drei", "@react-three/fiber", "motion", "three"],
	registryDependencies: [],
	props: [
		{ name: "items", type: "SpiralGalleryItem[]", required: true },
		{ name: "radius", type: "number", required: true },
		{ name: "tileHeight", type: "number", required: true },
		{ name: "tileAspect", type: "number", required: true },
		{ name: "tileCount", type: "number", required: true },
		{ name: "verticalSpacing", type: "number", required: true },
		{ name: "turnAngle", type: "number", required: true },
		{ name: "tileRotation", type: "number", required: true },
		{ name: "cornerRadius", type: "number", required: true },
		{ name: "curve", type: "number", required: true },
		{ name: "autoScroll", type: "number", required: true },
		{ name: "easing", type: "number", required: true },
		{ name: "input", type: "SpiralInput", required: true },
		{ name: "inputSpeed", type: "number", required: true },
		{ name: "drag", type: "boolean", required: true },
		{ name: "scrollSpread", type: "number", required: true },
		{ name: "scrollGrowth", type: "number", required: true },
		{ name: "wave", type: "number", required: true },
		{ name: "lensBlur", type: "number", required: true },
		{ name: "reveal", type: "boolean", required: true },
		{ name: "revealDuration", type: "number", required: true },
		{ name: "focusDuration", type: "number", required: true },
		{ name: "focusScale", type: "number", required: true },
		{ name: "autoScale", type: "boolean", required: true },
		{ name: "scale", type: "number", required: true },
		{ name: "className", type: "string" },
		{ name: "mode", type: "\"texture\" | \"scissor\"", description: "- texture: children render into an FBO each frame: Global post-processing will work on it.\n- scissor: a scissored pass painted on top of the composed frame. lighter, but excluded from global post-processing." },
		{ name: "priority", type: "number" },
		{ name: "zIndex", type: "number" },
		{ name: "transparent", type: "boolean" },
		{ name: "autoReflow", type: "boolean", description: "Re-measures the DOM rect every frame so the plane follows animated parents (motion, parallax).\nCosts one layout read per frame, so only enable it when needed." },
	],
	risk: { heavy: true, fullscreen: true, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
