import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "morph-slider",
	title: "Morph Slider",
	description: "",
	interaction: "",
	categories: ["Carousels"],
	tags: ["webgl", "hover", "cursor-tracking", "keyboard", "autoplay", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/components/morph-slider",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: ["gsap", "ogl"],
	registryDependencies: [],
	props: [
		{ name: "items", type: "MorphItem[]", default: "DEFAULT_ITEMS" },
		{ name: "startIndex", type: "number", default: "0" },
		{ name: "transition", type: "MorphTransition", default: "'melt'" },
		{ name: "duration", type: "number", default: "1.1" },
		{ name: "ease", type: "string", default: "'power2.inOut'" },
		{ name: "intensity", type: "number", default: "0.55" },
		{ name: "scale", type: "number", default: "2.4" },
		{ name: "aberration", type: "number", default: "0.35" },
		{ name: "drift", type: "number", default: "0.4" },
		{ name: "autoplay", type: "boolean", default: "false" },
		{ name: "autoplayDelay", type: "number", default: "4" },
		{ name: "loop", type: "boolean", default: "true" },
		{ name: "radius", type: "number", default: "16" },
		{ name: "overlayColor", type: "string", default: "'#000000'" },
		{ name: "showCaptions", type: "boolean", default: "true" },
		{ name: "showControls", type: "boolean", default: "true" },
		{ name: "showIndicators", type: "boolean", default: "true" },
		{ name: "className", type: "string", default: "''" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
