import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "instagram-card",
	title: "Instagram Card",
	description: "An interactive Instagram profile card component featuring gradient avatar border and 3D tilt effects on hover.",
	interaction: "Hover triggers a magnetic 3D tilt effect on the card and the link with spring physics.",
	categories: ["Cards"],
	tags: ["spring", "hover", "cursor-tracking"],
	inspiration: {
		source: "Great UI",
		url: "https://www.great-ui.com/components/instagram-card",
		author: "Saurabh Sharma",
		authorUrl: "https://github.com/Saurabh-2607",
		license: "Great UI Custom License",
		relationship: "port",
	},
	dependencies: ["motion"],
	registryDependencies: [],
	props: [
		{ name: "username", type: "string", required: true },
		{ name: "name", type: "string", default: "\"Instagram User\"" },
		{ name: "avatarUrl", type: "string", default: "\"https://ik.imagekit.io/niqgaoeg3/Gre…" },
		{ name: "bio", type: "string", default: "\"This is a placeholder bio for Instag…" },
		{ name: "posts", type: "string | number", default: "\"120\"" },
		{ name: "followers", type: "string | number", default: "\"10K\"" },
		{ name: "following", type: "string | number", default: "\"450\"" },
		{ name: "text", type: "string", default: "\"Follow me on\"" },
		{ name: "linkText", type: "string", default: "\"Instagram\"" },
		{ name: "href", type: "string" },
		{ name: "enableLinkTilt", type: "boolean", default: "true" },
		{ name: "linkTiltMaxRotate", type: "number", default: "5" },
		{ name: "enableCardTilt", type: "boolean", default: "true" },
		{ name: "cardTiltMaxRotate", type: "number", default: "5" },
		{ name: "className", type: "string" },
		{ name: "popoverClassName", type: "string" },
		{ name: "linkClassName", type: "string" },
		{ name: "labelClassName", type: "string" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
	gated: true,
});
