import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "line-sidebar",
	title: "Line Sidebar",
	description: "",
	interaction: "",
	categories: ["Navigation"],
	tags: ["cursor-tracking", "autoplay"],
	dependencies: [],
	registryDependencies: [],
	props: [
		{ name: "items", type: "string[]" },
		{ name: "accentColor", type: "string" },
		{ name: "textColor", type: "string" },
		{ name: "markerColor", type: "string" },
		{ name: "showIndex", type: "boolean" },
		{ name: "showMarker", type: "boolean" },
		{ name: "proximityRadius", type: "number" },
		{ name: "maxShift", type: "number" },
		{ name: "falloff", type: "Falloff" },
		{ name: "markerLength", type: "number" },
		{ name: "markerGap", type: "number" },
		{ name: "tickScale", type: "number" },
		{ name: "scaleTick", type: "boolean" },
		{ name: "itemGap", type: "number" },
		{ name: "fontSize", type: "number" },
		{ name: "smoothing", type: "number" },
		{ name: "defaultActive", type: "number | null" },
		{ name: "onItemClick", type: "((index: number, label: string) => void)" },
		{ name: "className", type: "string" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
