import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "linkedin-card",
	title: "LinkedIn Card",
	description: "An interactive LinkedIn profile card component that supports both static and animated 3D tilt effects.",
	interaction: "Hover triggers a magnetic 3D tilt effect on the card and the link with spring physics.",
	categories: ["Cards"],
	tags: ["spring", "hover", "cursor-tracking"],
	inspiration: {
		source: "Great UI",
		url: "https://www.great-ui.com/components/linkedin-card",
		author: "Saurabh Sharma",
		authorUrl: "https://github.com/Saurabh-2607",
		license: "Great UI Custom License",
		relationship: "port",
	},
	dependencies: ["motion"],
	registryDependencies: [],
	props: [
		{ name: "username", type: "string", required: true },
		{ name: "name", type: "string", default: "\"LinkedIn User\"" },
		{ name: "avatarUrl", type: "string", default: "\"https://ik.imagekit.io/niqgaoeg3/Gre…" },
		{ name: "bannerUrl", type: "string", default: "\"https://ik.imagekit.io/niqgaoeg3/ban…" },
		{ name: "headline", type: "string", default: "\"Software Engineer\"" },
		{ name: "connections", type: "string | number", default: "\"500+\"" },
		{ name: "location", type: "string", default: "\"San Francisco, CA\"" },
		{ name: "text", type: "string", default: "\"Connect on\"" },
		{ name: "linkText", type: "string", default: "\"LinkedIn\"" },
		{ name: "href", type: "string" },
		{ name: "enableLinkTilt", type: "boolean", default: "true" },
		{ name: "linkTiltMaxRotate", type: "number", default: "5" },
		{ name: "enableCardTilt", type: "boolean", default: "true" },
		{ name: "cardTiltMaxRotate", type: "number", default: "5" },
		{ name: "className", type: "string" },
		{ name: "popoverClassName", type: "string" },
		{ name: "linkClassName", type: "string" },
		{ name: "labelClassName", type: "string" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
	gated: true,
});
