import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "webcam-pixel-grid",
	title: "Webcam Pixel Grid",
	description: "",
	interaction: "",
	categories: ["Images", "3D & Canvas"],
	tags: ["canvas", "hover", "autoplay"],
	dependencies: [],
	registryDependencies: [],
	props: [
		{ name: "gridCols", type: "number", default: "64", description: "Number of columns in the grid" },
		{ name: "gridRows", type: "number", default: "48", description: "Number of rows in the grid" },
		{ name: "maxElevation", type: "number", default: "15", description: "Maximum elevation for motion detection" },
		{ name: "motionSensitivity", type: "number", default: "0.4", description: "Motion sensitivity (0-1)" },
		{ name: "elevationSmoothing", type: "number", default: "0.1", description: "Smoothing factor for elevation transitions" },
		{ name: "colorMode", type: "\"webcam\" | \"monochrome\"", default: "\"webcam\"", description: "Color mode: 'webcam' uses actual colors, 'monochrome' uses single color" },
		{ name: "monochromeColor", type: "string", default: "\"#00ff88\"", description: "Base color when in monochrome mode" },
		{ name: "backgroundColor", type: "string", default: "\"#0a0a0a\"", description: "Background color" },
		{ name: "mirror", type: "boolean", default: "true", description: "Whether to mirror the webcam feed" },
		{ name: "gapRatio", type: "number", default: "0.1", description: "Gap between cells (0-1, fraction of cell size)" },
		{ name: "invertColors", type: "boolean", default: "false", description: "Invert the colors" },
		{ name: "darken", type: "number", default: "0", description: "Darken factor (0-1, 0 = no darkening, 1 = fully dark)" },
		{ name: "borderColor", type: "string", default: "\"#ffffff\"", description: "Border color for cells" },
		{ name: "borderOpacity", type: "number", default: "0.08", description: "Border opacity (0-1)" },
		{ name: "className", type: "string", description: "Additional class name" },
		{ name: "onWebcamError", type: "((error: Error) => void)", description: "Callback when webcam access is denied" },
		{ name: "onWebcamReady", type: "(() => void)", description: "Callback when webcam is ready" },
	],
	risk: { heavy: true, fullscreen: true, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
