import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "photon-beam",
	title: "Photon Beam",
	description: "",
	interaction: "",
	categories: ["Backgrounds"],
	tags: ["webgl", "autoplay"],
	dependencies: ["three"],
	registryDependencies: [],
	props: [
		{ name: "colorBg", type: "string" },
		{ name: "colorLine", type: "string" },
		{ name: "colorSignal", type: "string" },
		{ name: "useColor2", type: "boolean" },
		{ name: "colorSignal2", type: "string" },
		{ name: "useColor3", type: "boolean" },
		{ name: "colorSignal3", type: "string" },
		{ name: "lineCount", type: "number" },
		{ name: "spreadHeight", type: "number" },
		{ name: "spreadDepth", type: "number" },
		{ name: "curveLength", type: "number" },
		{ name: "straightLength", type: "number" },
		{ name: "curvePower", type: "number" },
		{ name: "waveSpeed", type: "number" },
		{ name: "waveHeight", type: "number" },
		{ name: "lineOpacity", type: "number" },
		{ name: "signalCount", type: "number" },
		{ name: "speedGlobal", type: "number" },
		{ name: "trailLength", type: "number" },
		{ name: "bloomStrength", type: "number" },
		{ name: "bloomRadius", type: "number" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
