import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "model-viewer",
	title: "Model Viewer",
	description: "",
	interaction: "",
	categories: ["3D & Canvas"],
	tags: ["webgl", "hover", "cursor-tracking", "autoplay"],
	dependencies: ["@react-three/drei", "@react-three/fiber", "three"],
	registryDependencies: [],
	props: [
		{ name: "url", type: "string", required: true },
		{ name: "width", type: "string | number", default: "400" },
		{ name: "height", type: "string | number", default: "400" },
		{ name: "modelXOffset", type: "number", default: "0" },
		{ name: "modelYOffset", type: "number", default: "0" },
		{ name: "defaultRotationX", type: "number", default: "-50" },
		{ name: "defaultRotationY", type: "number", default: "20" },
		{ name: "defaultZoom", type: "number", default: "0.5" },
		{ name: "minZoomDistance", type: "number", default: "0.5" },
		{ name: "maxZoomDistance", type: "number", default: "10" },
		{ name: "enableMouseParallax", type: "boolean", default: "true" },
		{ name: "enableManualRotation", type: "boolean", default: "true" },
		{ name: "enableHoverRotation", type: "boolean", default: "true" },
		{ name: "enableManualZoom", type: "boolean", default: "true" },
		{ name: "ambientIntensity", type: "number", default: "0.3" },
		{ name: "keyLightIntensity", type: "number", default: "1" },
		{ name: "fillLightIntensity", type: "number", default: "0.5" },
		{ name: "rimLightIntensity", type: "number", default: "0.8" },
		{ name: "environmentPreset", type: "\"city\" | \"sunset\" | \"night\" | \"dawn\" | \"studio\" | \"apartm…", default: "\"forest\"" },
		{ name: "autoFrame", type: "boolean", default: "false" },
		{ name: "placeholderSrc", type: "string" },
		{ name: "showScreenshotButton", type: "boolean", default: "true" },
		{ name: "fadeIn", type: "boolean", default: "false" },
		{ name: "autoRotate", type: "boolean", default: "false" },
		{ name: "autoRotateSpeed", type: "number", default: "0.35" },
		{ name: "onModelLoaded", type: "(() => void)" },
	],
	risk: { heavy: true, fullscreen: true, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
