import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "halftone-reveal",
	title: "Halftone Reveal",
	description: "",
	interaction: "",
	categories: ["Images"],
	tags: ["webgl", "hover", "cursor-tracking", "autoplay", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/animations/halftone-reveal",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: ["ogl"],
	registryDependencies: [],
	props: [
		{ name: "src", type: "string", default: "DEFAULT_SRC" },
		{ name: "inkColor", type: "string", default: "'#141414'" },
		{ name: "paperColor", type: "string", default: "'#fff7e6'" },
		{ name: "mode", type: "Mode", default: "'mono'" },
		{ name: "dotSize", type: "number", default: "1" },
		{ name: "dotDensity", type: "number", default: "71" },
		{ name: "angle", type: "number", default: "45" },
		{ name: "shape", type: "Shape", default: "'circle'" },
		{ name: "contrast", type: "number", default: "1.15" },
		{ name: "invert", type: "boolean", default: "false" },
		{ name: "revealRadius", type: "number", default: "0.4" },
		{ name: "edge", type: "number", default: "0.8" },
		{ name: "follow", type: "number", default: "0.37" },
		{ name: "idleReveal", type: "number", default: "0" },
		{ name: "trigger", type: "Trigger", default: "'hover'" },
		{ name: "borderRadius", type: "string", default: "'16px'" },
		{ name: "className", type: "string", default: "''" },
		{ name: "style", type: "CSSProperties" },
	],
	risk: { heavy: true, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
