import { defineComponent } from "@/registry/schema";

export default defineComponent({
	slug: "pixel-swap",
	title: "Pixel Swap",
	description: "",
	interaction: "",
	categories: ["Images"],
	tags: ["hover", "keyboard", "responsive"],
	inspiration: {
		source: "React Bits",
		url: "https://reactbits.dev/animations/pixel-swap?pattern=right-to-left",
		authorUrl: "https://reactbits.dev",
		relationship: "adaptation",
	},
	dependencies: [],
	registryDependencies: [],
	props: [
		{ name: "firstContent", type: "ReactNode", required: true },
		{ name: "secondContent", type: "ReactNode", required: true },
		{ name: "pixelSize", type: "number", default: "64" },
		{ name: "gap", type: "number", default: "0" },
		{ name: "pixelRadius", type: "number", default: "0" },
		{ name: "pixelSpin", type: "number", default: "0" },
		{ name: "pixelScale", type: "number", default: "0.35" },
		{ name: "fade", type: "boolean", default: "true" },
		{ name: "duration", type: "number", default: "1400" },
		{ name: "pixelDuration", type: "number", default: "450" },
		{ name: "pattern", type: "PixelSwapPattern", default: "'random'" },
		{ name: "randomness", type: "number", default: "0" },
		{ name: "easing", type: "string", default: "'cubic-bezier(0.22, 1, 0.36, 1)'" },
		{ name: "trigger", type: "PixelSwapTrigger", default: "'hover'" },
		{ name: "initialActive", type: "boolean", default: "false" },
		{ name: "active", type: "boolean" },
		{ name: "onActiveChange", type: "((active: boolean) => void)" },
		{ name: "onComplete", type: "((active: boolean) => void)" },
		{ name: "aspectRatio", type: "string", default: "'16 / 10'" },
		{ name: "className", type: "string", default: "''" },
		{ name: "style", type: "CSSProperties" },
	],
	risk: { heavy: false, fullscreen: false, clientOnly: false },
	rating: 5,
	status: "needs-review",
});
